### ISSUE TITLE
Just want to say thank you!

### ISSUE THREAD

**Issue by paulogdm** [carlospliego/sails-token-auth-setup#2]
Man, you have no idea how grateful i am.
Waterlock (no doc), sails-auth (weird things under the hood), sails-auth-generator (fail), ..... they are nothing. Ty for this repo!

**Comment by carlospliego** [comment]
@paulogdm I experienced your pain. Thats why I created this little repo. Feel free to PR if you have any improvements.

**Comment by paulogdm** [comment]
Hello. Can you please take a look at this: https://github.com/paulogdm/betti/blob/master/betti-sails/config/passport.js

My point is, the LocalStrategy is not being called! Any idea why?
Maybe a bad config/*js file?
Just double checked your files and everything seems to be equal.
Debugging it with postman and 
{ "success": false,
    "message": "invalidLogin"} is being received.
Thanks in advance.

**Comment by carlospliego** [comment]
There seems to be a number of problems with how you're doing the authentication.
I was able to create a user via postman: 

```
{
    "user_posts": [],
    "user_following": [],
    "user_followers": [],
    "login": "carlos",
    "name": "carlos",
    "password": "1234",
    "birthday": "1234",
    "style_profile": 0,
    "style_bar": 0,
    "createdAt": "2016-05-24T04:35:16.746Z",
    "updatedAt": "2016-05-24T04:35:16.746Z"
  }
```

1 ) you're storing the password in literal text. I really recommend encrypting the string. 
2 ) you're getting an invalid login because you're trying to compare the passwords on login using a bcrypt algorithm... it wont work if the password is not encrypted. 

I wish you the best... if you need help, open up a stackoverflow question and send me the link.

**Comment by paulogdm** [comment]
Solved!!!

This little trick did the job:

Under "passport.js"
passport.use(new LocalStrategy({
    **usernameField: 'login',
    passwordField: 'password'**
    },
    function(login, password, done) {
        User.find({login:login}).exec(function(err, user) {
